version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=AIzaSyD2ONKYAQgKKb_P1mn9Ta_mpfGnCzRcydM
      - WATCHPACK_POLLING=true
    command: sh -c "npm install && npm run dev"
    stdin_open: true
    tty: true 